title: 仔仔的博客
description: > # this means to ignore newlines until "baseurl:"
  Blog with theme Future Imperfect<br>
baseurl: 
url: "https://future-imperfect.kaptn.ru" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: '仔仔'
  last_name: 'dhy'
  cv: ''
  avatar: ''
  github_username:  dhy824  
  email: 1832840839@qq.com
  vk_id: 
  telegram_name: 仔仔
  logo: ''

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html


